prediction_force:
  general:
    description: "Estrategia de prediccion para opciones binarias"
    author: "BetaBot Team"
    symbol: EURUSD-OTC
    risk_level: "medium"

  asset_config:
    digits: 5
    tolerance: 0.0002
    truncate: false
    expiration: 1  # Expiración en minutos para IQOption
    timeframe_base: 1 # Tiempo base para análisis expresado en minutos

  strategy_params:
    (Configuracion de parametros de la estrategia)  # Configuración de análisis y métricas
