# File: config/strategies/crypto/prediction_force.yaml
# Este archivo configura la estrategia "Prediction Force" adaptada al mercado 
# Incluye análisis multifractal, gestión de riesgo y parámetros específicos para criptomonedas.
# Esta configuracion se utiliza como fallback en caso de que un activo no tenga
# una configuracion especifica o tenga parametros mal configurados para la estrategia de criptomonedas.
# Se recomienda ajustar los parámetros según el activo específico y las condiciones del mercado.

# Archivo base de estrategia Prediction Force para criptomonedas.
# Adaptación estructural de la versión Forex con ajustes para criptoactivos.
# Soporta trading en múltiples temporalidades: 1m, 15m, 1h, 4h, 1d

strategy:
  name: "prediction_force"
  market: "crypto"
  version: "2.0.0"
  enabled: true

  general:
    description: "Estrategia Prediction Force adaptada al mercado cripto (scalping + swing)"
    author: "BetaBot Team"
    risk_level: "medium"

  timeframe_base: 300     # 5 minutos como base para análisis general
  tick_scale: 0.01        # Escala mínima de cambio en precio cripto (depende del activo)
  slippage_limit: 0.3     # Deslizamiento máximo aceptado (en %)

  strategy_parameters:
    enabled: true
    analysis:
      dominance_threshold: 78
      strong_dominance_threshold: 87
      ratio_threshold: 68
      confidence_reduction: 30
      confidence_boost: 8
      volume_confirmation_threshold: 72
      volume_contradiction_threshold: 76
      use_volume_analysis: true
      tick_velocity_threshold:
        crypto: 3.2
      poc_distance_factor: 2.5
      required_conditions: 4
      lookback_candles:
        crypto: 18
      min_probability: 33
      use_poc: true
      use_value_area: true
      min_ticks_volume: 20
      advanced_volume_analysis: true

      metrics_thresholds:
        poc_min_volume: 4
        value_area_default_percentage: 0.68
        tick_processing_frequency: 4

    multi_timeframe_analysis:
      enabled: true
      layers:
        scalping:
          timeframe: 1m
          expiration: 60s
          lookback_candles: 12
          metrics_profile: "micro"
          confidence_threshold: 75
          max_duration_seconds: 180
          allow_overlap: false
        short_term:
          timeframe: 15m
          expiration: 1h
          lookback_candles: 30
          metrics_profile: "contextual"
          confidence_threshold: 80
        mid_term:
          timeframe: 1h
          expiration: 4h
          lookback_candles: 48
          metrics_profile: "trend_volume"
          confidence_threshold: 85
        long_term:
          timeframe: 4h
          expiration: 1d
          lookback_candles: 72
          metrics_profile: "macro_trend_strength"
          confidence_threshold: 90

    multifractal_analysis:
      enabled: true
      base_timeframe: 15
      sub_timeframes: [1, 3, 5, 15]
      consensus_threshold: 65
      follow_trend: false
      extended_lookback: false
      trend_window: 25
      trend_threshold: 70
      min_confidence: 75
      probability_boost: 7

    candle_patterns:
      enabled: true
      lookback: 12
      doji_threshold: 0.2
      strong_trend_threshold: 0.87
      pinbar_body_ratio: 0.22
      pinbar_shadow_ratio: 0.6
      engulfing_min_body_ratio: 0.78

    support_resistance_analysis:
      enabled: true
      lookback_candles: 8

    confidence_adjustment_factors:
      price_action_patterns:
        doji: -12
        pinbar: 7
        engulfing: 10
        inside_bar: -3
        outside_bar: 5

      support_resistance_status:
        consolidating_at_poc: -7
        rejection_near_poc: 18
        breaking_level: 12
        stagnation_or_range: -4

      volume_confirm_boost_high: 6
      volume_confirm_boost_medium: 5
      volume_breakout_boost: 10
      volume_indecision_boost: 9
      rejection_volume_boost: 7

      volume_contradict_penalty_high: 10
      volume_contradict_penalty_medium: 7

      momentum_strength_multiplier: 11
      breakout_strength_multiplier: 9
      rejection_strength_multiplier: 8

      max_confidence_high_vol: 88
      max_confidence_breakout: 91
      max_confidence_rejection: 82
      max_confidence_indecision: 72

      min_confidence_high_vol_contradict: 53
      min_confidence_medium_vol_contradict: 48

    trade:
      amount_type: fixed       # Si se usa "fixed" se usa  fixed_amount, si es "percentage" se usa percentage   
      fixed_amount: 100.0      # Monto fijo por operación
      percentage: 0.02         # Porcentaje del capital disponible
      max_trade_amount: 1000.0 # Monto máximo por operación si se usa "fixed" o "percentage"

      stop_loss:
        enabled: true
        type: atr_based
        value_pips: null   # No se usa en cripto, se define por ATR si corresponde
        trailing:
          enabled: true
          start_pips: 1.5
          step_pips: 0.5
          max_distance_pips: 5.0

      take_profit:
        enabled: true
        type: rr_ratio
        value_pips: null
        rr_ratio: 2.5

      cooldown_seconds: 600
      position_scaling:
        enabled: true
        confidence_tiers:
          - threshold: 75
            multiplier: 25
          - threshold: 80
            multiplier: 50
          - threshold: 85
            multiplier: 75
          - threshold: 90
            multiplier: 100
        max_amount: 3000.0

    default_probability_thresholds:
      default: 80
      crypto:
        low_volatility: 78
        medium_volatility: 82
        high_volatility: 85

    use_correlations:
      crypto: true

    global_live_candle:
      enabled: true
      window_size: 90  # Cripto tiene volatilidad rápida, ventana más breve
      metrics_analysis:
        - micro_rsi
        - micro_macd
        - micro_momentum_score
        - micro_reversal_score
        - tick_entropy
        - tick_cluster_density
        - micro_zones_concentration
        - micro_sr_bias
        - micro_close_position
        - micro_pattern_score
        - micro_movement_sequences
        - micro_cluster_intensity
        - velocity_avg
        - acceleration_avg
        - jerk
        - tick_frequency
        - direction_changes
        - max_consecutive_direction
        - net_direction_score
        - micro_volatility_spikes
        - streak_volatility
        - tick_pressure
        - momentum_score_combined
        - wap
        - price_range
        - price_std
        - price_skewness
        - kurtosis
        - price_entropy
        - price_mode_count
        - candle_displacement
        - tick_count
        - volume_total
        - volume_directional
        - volume_delta
        - tick_volume_std
        - tick_volume_burst
        - poc_intravela
        - value_area
        - vertical_volume
        - volume_distribution
        - volume_dominance
        - volume_nodes
        - lvn_nodes
        - liquidity_zone_proximity
        - poc_static
        - poc_dynamic
        - volume_profile_map
        - value_area_range
        - high_volume_nodes
        - low_volume_nodes
        - composite_profile
        - volume_skew
        - volume_kurtosis
        - volume_std
        - volume_entropy
        - volume_mode_count
        - volume_spread_ratio

    sliding_window_metrics:
      enabled: true
      window_size_seconds: 5
      metrics_to_update:
        - micro_rsi
        - micro_macd
        - micro_momentum_score
        - micro_reversal_score
        - tick_entropy
        - tick_cluster_density
        - micro_zones_concentration
        - micro_sr_bias
        - micro_close_position
        - micro_pattern_score
        - micro_movement_sequences
        - micro_cluster_intensity
        - velocity_avg
        - acceleration_avg
        - jerk
        - tick_frequency
        - direction_changes
        - max_consecutive_direction
        - net_direction_score
        - micro_volatility_spikes
        - streak_volatility
        - tick_pressure
        - momentum_score_combined
        - wap
        - price_range
        - price_std
        - price_skewness
        - kurtosis
        - price_entropy
        - price_mode_count
        - candle_displacement
        - tick_count
        - volume_total
        - volume_directional
        - volume_delta
        - tick_volume_std
        - tick_volume_burst
        - poc_intravela
        - value_area
        - vertical_volume
        - volume_distribution
        - volume_dominance
        - volume_nodes
        - lvn_nodes
        - liquidity_zone_proximity
        - poc_static
        - poc_dynamic
        - volume_profile_map
        - value_area_range
        - high_volume_nodes
        - low_volume_nodes
        - composite_profile
        - volume_skew
        - volume_kurtosis
        - volume_std
        - volume_entropy
        - volume_mode_count
        - volume_spread_ratio
