metrics:
  momentum_intrabar:
    description: "Configuración para métricas de momentum intrabar"
    velocity_avg:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    acceleration_avg:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    jerk:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    tick_frequency:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    direction_changes:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    max_consecutive_direction:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    net_direction_score:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    micro_volatility_spikes:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    streak_volatility:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    tick_pressure:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    momentum_score_combined:
      enabled: true 
      (Configuraciones específicas para esta métrica)