metrics:
  price_stats:
    description: "Configuración para métricas de price_stats"
    wap:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    price_range:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    price_std:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    price_skewness:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    kurtosis:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    price_entropy:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    price_mode_count:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    candle_displacement:
      enabled: true 
      (Configuraciones específicas para esta métrica)