metrics:
  volume_intrabar:
    description: "Configuración para métricas de volumen intrabar"
    tick_count:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    volume_total:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    volume_directional:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    volume_delta:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    tick_volume_std:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    tick_volume_burst:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    poc_intravela:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    value_area:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    vertical_volume:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    volume_distribution:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    volume_dominance:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    volume_nodes:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    lvn_nodes:
      enabled: true 
      (Configuraciones específicas para esta métrica)
    liquidity_zone_proximity:
      enabled: true 
      (Configuraciones específicas para esta métrica)