prediction_force:
  general:
    description: "Estrategia de predicción para criptomonedas"
    author: "BetaBot Team"
    symbol: BTCUSDT
    risk_level: "high"

  asset_config:
    digits: 5
    tolerance: 0.0002
    truncate: false
    timeframe_base: 5 # Tiempo base para análisis expresado en minutos

  strategy_params:
    (Configuracion de parametros de la estrategia)  # Configuración de análisis y métricas
