# File: config/strategies/binary_options/EURUSD.yaml
# Configuración específica para el par EUR/USD en la estrategia Prediction Force
# Sobrescribe todos los parámetros relevantes para garantizar autonomía y granularidad

prediction_force:
  general:
    description: "Estrategia optimizada para opciones binarias en EUR/USD, considerando alta liquidez, volatilidad moderada y correlaciones con otros pares"
    author: "BetaBot Team"
    symbol: EURUSD
    risk_level: "medium-high"  # Refleja volatilidad en eventos económicos

  asset_config:
    digits: 5                  # 5 dígitos para precisión en cotizaciones
    tolerance: 0.00015         # Tolerancia ajustada para movimientos precisos
    truncate: false            # Sin truncar para mantener precisión

  strategy_parameters:
    enabled: true
    timeframe_base: 300       # 5 minutos, adecuado para sesiones activas
    expiration_base: 60       # Expiración alineada con timeframe
    analysis:
      dominance_threshold: 85          # Más estricto por alta liquidez
      strong_dominance_threshold: 90   # Umbral para señales fuertes
      ratio_threshold: 75              # Ratio alcista/bajista ajustado
      confidence_reduction: 30         # Menor reducción por estabilidad
      confidence_boost: 7              # Mayor boost por confirmaciones fiables
      volume_confirmation_threshold: 80 # Umbral alto por volumen constante
      volume_contradiction_threshold: 82 # Umbral para contradicciones
      use_volume_analysis: true
      tick_velocity_threshold:
        forex: 4.0                    # Ajustado para alta actividad
      poc_distance_factor: 2.5        # Menor distancia al POC por movimientos rápidos
      required_conditions: 6          # Más condiciones para señales robustas
      min_probability: 25             # Probabilidad mínima más alta
      use_poc: true                   # Habilitar análisis de POC
      use_value_area: true            # Habilitar área de valor
      min_ticks_volume: 22           # Más ticks por alta liquidez
      advanced_volume_analysis: false # Desactivado para evitar ruido
      metrics_thresholds:
        poc_min_volume: 4            # Mayor volumen para POC
        value_area_default_percentage: 0.75 # Área de valor más amplia
        tick_processing_frequency: 4  # Mayor frecuencia para movimientos rápidos

    multifractal_analysis:
      enabled: true
      base_timeframe: 3              # 3 minutos para tendencias cortas
      sub_timeframes: [1, 2, 3]      # Sub-timeframes más cortos
      consensus_threshold: 70        # Umbral más alto para consenso
      follow_trend: true             # Seguir tendencia en EUR/USD
      extended_lookback: true        # Ventana extendida para tendencias
      trend_window: 20              # Menor ventana por movimientos rápidos
      trend_threshold: 80           # Umbral más alto para fuerza de tendencia
      min_confidence: 80            # Confianza mínima más alta
      probability_boost: 7          # Mayor boost para señales multifractales

    candle_patterns:
      enabled: true
      lookback: 10                  # Menor lookback por movimientos rápidos
      doji_threshold: 0.25          # Más estricto para detectar dojis
      strong_trend_threshold: 0.90  # Umbral más alto para tendencias fuertes
      pinbar_body_ratio: 0.15       # Más estricto para pinbars
      pinbar_shadow_ratio: 0.65     # Ajustado para sombras más largas
      engulfing_min_body_ratio: 0.85 # Más estricto para patrones engulfing

    support_resistance_analysis:
      enabled: true
      lookback_candles: 10          # Mayor lookback para niveles clave

    confidence_adjustment_factors:
      price_action_patterns:
        doji: -10                  # Menor penalización por doji
        pinbar: 7                  # Mayor boost por pinbars
        engulfing: 15              # Mayor boost por engulfing
        inside_bar: -7             # Mayor penalización por inside bars
        outside_bar: 7             # Mayor boost por outside bars
      support_resistance_status:
        consolidating_at_poc: -8   # Menor penalización por consolidación
        rejection_near_poc: 20     # Mayor boost por rechazos
        breaking_level: 12         # Mayor boost por rupturas
        stagnation_or_range: -7    # Mayor penalización por rangos
      volume_confirm_boost_high: 7
      volume_confirm_boost_medium: 5
      volume_breakout_boost: 12
      volume_indecision_boost: 8
      rejection_volume_boost: 7
      volume_contradict_penalty_high: 12
      volume_contradict_penalty_medium: 10
      momentum_strength_multiplier: 18
      breakout_strength_multiplier: 12
      rejection_strength_multiplier: 12
      max_confidence_high_vol: 88
      max_confidence_breakout: 92
      max_confidence_rejection: 85
      max_confidence_indecision: 75
      min_confidence_high_vol_contradict: 55
      min_confidence_medium_vol_contradict: 55

    trade:
      amount: 15.0                 # Monto base ajustado
      cooldown_seconds: 240        # 4 minutos, más corto por alta actividad
      position_scaling:
        enabled: true
        confidence_tiers:
          - threshold: 65
            multiplier: 0.8
          - threshold: 75
            multiplier: 1.2
          - threshold: 85
            multiplier: 2.5
          - threshold: 90
            multiplier: 3.5
          - threshold: 95
            multiplier: 4.5
        max_amount: 250.0         # Límite máximo reducido para riesgo

    default_probability_thresholds:
      forex:
        normal: 87              # Más alto para condiciones normales
        volatile: 90            # Más alto para condiciones volátiles

    use_correlations:
      forex: true               # Habilitar correlaciones (USD/CHF, GBP/USD)

    global_live_candle:
      enabled: true
      window_size: 120           # 45 minutos, ajustado para contexto más corto
      metrics_analysis:
        - micro_rsi
        - micro_macd
        - micro_momentum_score
        - tick_entropy
        - tick_cluster_density
        - micro_zones_concentration
        - net_direction_score
        - candle_displacement
        - poc_intravela
        - volume_dominance
        - price_std
        - tick_frequency
        - vertical_volume

    sliding_window_metrics:
      enabled: true
      window_size_seconds: 4  # Ventana corta para alta frecuencia
      metrics_to_update:
        - tick_velocity
        - tick_frequency
        - direction_changes
        - net_direction_score
        - micro_reversal_score
        - micro_volatility_spikes
        - tick_pressure
        - tick_entropy
        - micro_pattern_score
        - price_std
        - volume_delta
        - tick_cluster_density
        - micro_zones_concentration
        - momentum_score_combined