# Template base para activos de binary options
template_type: binary_options
prediction_force:
  general:
    description: "Estrategia de prediccion para opciones binarias"
    author: "BetaBot Team"
    risk_level: "medium"
  
  asset_config:
    digits: 5
    tolerance: 0.0002
    truncate: false
    expiration: 1
    timeframe_base: 1
  
  strategy_params:
    enabled: true
    # Parámetros comunes para binary options