# Template base para criptomonedas
template_type: crypto
prediction_force:
  general:
    description: "Estrategia de prediccion para criptomonedas"
    author: "BetaBot Team"
    risk_level: "high"
  
  asset_config:
    digits: 8
    tolerance: 0.001
    truncate: false
    timeframe_base: 1
  
  strategy_params:
    enabled: true
    # Parámetros comunes para crypto