# Template base para forex tradicional
template_type: forex_traditional
prediction_force:
  general:
    description: "Estrategia de prediccion para forex tradicional"
    author: "BetaBot Team"
    risk_level: "medium"
  
  asset_config:
    digits: 5
    tolerance: 0.0002
    truncate: false
    timeframe_base: 5
  
  strategy_params:
    enabled: true
    # Parámetros comunes para forex tradicional